# Generated by Django 3.2.4 on 2021-07-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
